name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start application with PM2
        run: |
          npm install -g pm2
          pm2 start dist/index.js --name expense-app

      - name: Restart PM2 process
        run: |
          pm2 restart expense-app || echo "process not running"

      - name: Save PM2 process list
        run: pm2 save

    
